server:
  port: 9090
  
spring :
  datasource:
    url: jdbc:oracle:thin:@61.78.121.242:8877:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: dal
    password: gona1234!
    
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: dalpool
      
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp